name: Deploy to S3

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string
      source_dir:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}  # Correct reference to region

      - name: Sync files to S3
        run: |
          aws s3 sync ${GITHUB_WORKSPACE}/${{ inputs.source_dir }} s3://${{ inputs.bucket_name }} --delete  # Corrected sync command
