# repo1/.github/workflows/reusable-deploy-to-s3.yml
name: Reusable Deploy to S3 Workflow

on:
  workflow_call:  # This makes the workflow reusable
    inputs:
      bucket_name:
        description: 'The name of the S3 bucket'
        required: true
        type: string
      region:
        description: 'The AWS region of the S3 bucket'
        required: true
        type: string
      source_dir:
        description: 'The directory to upload to S3'
        required: true
        type: string

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Sync files to S3
        run: |
          aws s3 sync ${GITHUB_WORKSPACE}/${{ inputs.source_dir }} s3://${{ inputs.bucket_name }} --delete
